### PR TITLE
feat: copy over `#[cfg(...)]` into `from()` impl

### LINKED ISSUE #13: `from` breaks when a struct member is feature gated
Generation of `from()` breaks when some struct fields are feature gated but not used.

E.g.:

```
❯ cat -p src/main.rs 
use optfield::optfield;

#[optfield(OptFoo, attrs, field_attrs, from)]
struct Foo {
    a: String,
    #[cfg(feature = "foo")]
    b: String,
}

fn main() {
    println!("Hello, world!");
}
```

... expands to this:

```
#![feature(prelude_import)]                                                    
#[prelude_import]    
use std::prelude::rust_2021::*;
#[macro_use]                        
extern crate std;      
use optfield::optfield;
struct Foo {
    a: String,      
}                                      
struct OptFoo {
    a: Option<String>,                                                                                                                                         
}                                    
impl From<Foo> for OptFoo {                                                                                                                                    
    fn from(item: Foo) -> OptFoo {
        OptFoo {
            a: Some(item.a),                                                   
            b: Some(item.b),
        }     
    }                      
}             
fn main() {
    {
        ::std::io::_print(format_args!("Hello, world!\n"));
    };                        
}
```

... which, unless the feature foo is enabled, fails compiling:

```
❯ cargo build
   Compiling optfield_cfgtest v0.1.0 (/home/kaspar/tmp/optfield_cfgtest)
error[E0560]: struct `OptFoo` has no field named `b`
 --> src/main.rs:7:5
  |
7 |     b: String,
  |     ^ `OptFoo` does not have this field
  |
  = note: all struct fields are already assigned

error[E0609]: no field `b` on type `Foo`
 --> src/main.rs:7:5
  |
7 |     b: String,
  |     ^ unknown field
  |
help: a field with a similar name exists
  |
7 |     a: String,
  |     ~


```

### PR DESCRIPTION
**Pull request by kaspar030**
I gave this a shot and it seems simple. My macro-fu is at best medium, I can't say if this would have any side effects.

Fixes #13.

### CODE REVIEW

**Comment by kaspar030** [comment]
I tested this, it works fine for my actual use case, https://github.com/embassy-rs/embassy/pull/2213, allowing me to replace the custom code for this. :+1:

**Comment by roignpar** [comment]
Thank you for the fix!
I fixed the clippy warnings. Could you please rebase?

**Comment by roignpar** [comment]
I will merge this and add some more changes on top. Some tests and the equivalent fix for `merge_fn`.

**Comment by kaspar030** [comment]
Great, thanks!

**Pull request merged**
